<h1> Homework Questions for Session 1 Introduction </h1>  

 [Link to Session 1 Homework Questions](https://github.com/DataTalksClub/machine-learning-zoomcamp/blob/master/cohorts/2023/01-intro/homework.md)

<h2> Question 1 </h2>

What's the version of Pandas that you installed?

You can get the version information using the __version__ field:

In [3]:
from platform import python_version
print(python_version())

3.11.4


In [4]:
import wget
url = 'https://raw.githubusercontent.com/alexeygrigorev/datasets/master/housing.csv'
filename = wget.download(url)
filename

'housing.csv'

`Answer: 3.11.4`

<h2> Question 2 </h2>

How many columns are in the dataset?
- 10
- 6560
- 10989
- 20640

In [5]:
import pandas as pd
import numpy as np

In [6]:
df=pd.read_csv('housing.csv')

In [7]:
df.columns

Index(['longitude', 'latitude', 'housing_median_age', 'total_rooms',
       'total_bedrooms', 'population', 'households', 'median_income',
       'median_house_value', 'ocean_proximity'],
      dtype='object')

In [8]:
len(df.columns)

10

`Answer: 10`

<h2> Question 3 </h2>


Which columns in the dataset have missing values?
- total_rooms
- total_bedrooms
- both of the above
- no empty columns in the dataset

In [9]:
df.isnull().sum()

longitude               0
latitude                0
housing_median_age      0
total_rooms             0
total_bedrooms        207
population              0
households              0
median_income           0
median_house_value      0
ocean_proximity         0
dtype: int64

`Answer: total_bedrooms`

<h2> Question 4 </h2>


How many unique values does the ocean_proximity column have?
- 3
- 5
- 7
- 9

In [10]:
df.ocean_proximity.unique()

array(['NEAR BAY', '<1H OCEAN', 'INLAND', 'NEAR OCEAN', 'ISLAND'],
      dtype=object)

In [11]:
len(df.ocean_proximity.unique())

5

`Answer: 5`

<h2> Question 5 </h2>


What's the average value of the median_house_value for the houses located near the bay?

- 49433
- 124805
- 259212
- 380440

In [12]:
bay_house=df[df.ocean_proximity=='NEAR BAY']
bay_house.head()

longitude  latitude  housing_median_age  total_rooms  total_bedrooms  \
0    -122.23     37.88                41.0        880.0           129.0   
1    -122.22     37.86                21.0       7099.0          1106.0   
2    -122.24     37.85                52.0       1467.0           190.0   
3    -122.25     37.85                52.0       1274.0           235.0   
4    -122.25     37.85                52.0       1627.0           280.0   

   population  households  median_income  median_house_value ocean_proximity  
0       322.0       126.0         8.3252            452600.0        NEAR BAY  
1      2401.0      1138.0         8.3014            358500.0        NEAR BAY  
2       496.0       177.0         7.2574            352100.0        NEAR BAY  
3       558.0       219.0         5.6431            341300.0        NEAR BAY  
4       565.0       259.0         3.8462            342200.0        NEAR BAY

In [13]:
bay_house.describe()

longitude     latitude  housing_median_age   total_rooms  \
count  2290.000000  2290.000000         2290.000000   2290.000000   
mean   -122.260694    37.801057           37.730131   2493.589520   
std       0.147004     0.185434           13.070385   1830.817022   
min    -122.590000    37.350000            2.000000      8.000000   
25%    -122.410000    37.730000           29.000000   1431.250000   
50%    -122.250000    37.790000           39.000000   2083.000000   
75%    -122.140000    37.907500           52.000000   3029.750000   
max    -122.010000    38.340000           52.000000  18634.000000   

       total_bedrooms   population   households  median_income  \
count     2270.000000  2290.000000  2290.000000    2290.000000   
mean       514.182819  1230.317467   488.616157       4.172885   
std        367.887605   885.899035   350.598369       2.017427   
min          1.000000     8.000000     1.000000       0.499900   
25%        289.000000   718.250000   275.000000       2.834750   
50%        423.000000  1033.500000   406.000000       3.818650   
75%        628.750000  1495.000000   599.250000       5.054425   
max       3226.000000  8276.000000  3589.000000      15.000100   

       median_house_value  
count         2290.000000  
mean        259212.311790  
std         122818.537064  
min          22500.000000  
25%         162500.000000  
50%         233800.000000  
75%         345700.000000  
max         500001.000000

In [26]:
bay_house.median_house_value.mean()

259212.31179039303

`Answer: 259212`

<h2> Question 6 </h2>    

1. Calculate the average of total_bedrooms column in the dataset.   
2. Use the fillna method to fill the missing values in total_bedrooms with the mean value from the previous step.  
3. Now, calculate the average of total_bedrooms again.  
4. Has it changed?  

- Yes
- No

In [14]:
average_bedrooms=df.total_bedrooms.mean()
print(average_bedrooms)

537.8705525375618


In [15]:
df.fillna(average_bedrooms)

longitude  latitude  housing_median_age  total_rooms  total_bedrooms  \
0        -122.23     37.88                41.0        880.0           129.0   
1        -122.22     37.86                21.0       7099.0          1106.0   
2        -122.24     37.85                52.0       1467.0           190.0   
3        -122.25     37.85                52.0       1274.0           235.0   
4        -122.25     37.85                52.0       1627.0           280.0   
...          ...       ...                 ...          ...             ...   
20635    -121.09     39.48                25.0       1665.0           374.0   
20636    -121.21     39.49                18.0        697.0           150.0   
20637    -121.22     39.43                17.0       2254.0           485.0   
20638    -121.32     39.43                18.0       1860.0           409.0   
20639    -121.24     39.37                16.0       2785.0           616.0   

       population  households  median_income  median_house_value  \
0           322.0       126.0         8.3252            452600.0   
1          2401.0      1138.0         8.3014            358500.0   
2           496.0       177.0         7.2574            352100.0   
3           558.0       219.0         5.6431            341300.0   
4           565.0       259.0         3.8462            342200.0   
...           ...         ...            ...                 ...   
20635       845.0       330.0         1.5603             78100.0   
20636       356.0       114.0         2.5568             77100.0   
20637      1007.0       433.0         1.7000             92300.0   
20638       741.0       349.0         1.8672             84700.0   
20639      1387.0       530.0         2.3886             89400.0   

      ocean_proximity  
0            NEAR BAY  
1            NEAR BAY  
2            NEAR BAY  
3            NEAR BAY  
4            NEAR BAY  
...               ...  
20635          INLAND  
20636          INLAND  
20637          INLAND  
20638          INLAND  
20639          INLAND  

[20640 rows x 10 columns]

In [16]:
average_bedrooms.mean()

537.8705525375618

In [17]:
difference=average_bedrooms.mean()-df.total_bedrooms.mean()
print(difference)

0.0


`Anwer: No`

<h2> Question 7 </h2>

1. Select all the options located on islands.
2. Select only columns housing_median_age, total_rooms, total_bedrooms.
3. Get the underlying NumPy array. Let's call it X.
4. Compute matrix-matrix multiplication between the transpose of X and X. To get the transpose, use X.T. Let's call the result XTX.
5. Compute the inverse of XTX.
6. Create an array y with values [950, 1300, 800, 1000, 1300].
7. Multiply the inverse of XTX with the transpose of X, and then multiply the result by y. Call the result w.
8. What's the value of the last element of w?

- -1.4812
- 0.001
- 5.6992
- 23.1233

In [18]:
island=df[df['ocean_proximity']=='ISLAND']
island.head()

longitude  latitude  housing_median_age  total_rooms  total_bedrooms  \
8314    -118.32     33.35                27.0       1675.0           521.0   
8315    -118.33     33.34                52.0       2359.0           591.0   
8316    -118.32     33.33                52.0       2127.0           512.0   
8317    -118.32     33.34                52.0        996.0           264.0   
8318    -118.48     33.43                29.0        716.0           214.0   

      population  households  median_income  median_house_value  \
8314       744.0       331.0         2.1579            450000.0   
8315      1100.0       431.0         2.8333            414700.0   
8316       733.0       288.0         3.3906            300000.0   
8317       341.0       160.0         2.7361            450000.0   
8318       422.0       173.0         2.6042            287500.0   

     ocean_proximity  
8314          ISLAND  
8315          ISLAND  
8316          ISLAND  
8317          ISLAND  
8318          ISLAND

In [19]:
X=island[['housing_median_age', 'total_rooms', 'total_bedrooms']]
X

housing_median_age  total_rooms  total_bedrooms
8314                27.0       1675.0           521.0
8315                52.0       2359.0           591.0
8316                52.0       2127.0           512.0
8317                52.0        996.0           264.0
8318                29.0        716.0           214.0

In [20]:
XT = X.T
XT

8314    8315    8316   8317   8318
housing_median_age    27.0    52.0    52.0   52.0   29.0
total_rooms         1675.0  2359.0  2127.0  996.0  716.0
total_bedrooms       521.0   591.0   512.0  264.0  214.0

In [21]:
X.shape

(5, 3)

In [22]:
XT.shape

(3, 5)

In [23]:
XTX = np.dot(XT, X)
XTX

array([[9.6820000e+03, 3.5105300e+05, 9.1357000e+04],
       [3.5105300e+05, 1.4399307e+07, 3.7720360e+06],
       [9.1357000e+04, 3.7720360e+06, 9.9835800e+05]])

In [24]:
XTX_inv = np.linalg.inv(XTX)

XTX_inv, XTX_inv.sum()

(array([[ 9.19403586e-04, -3.66412216e-05,  5.43072261e-05],
        [-3.66412216e-05,  8.23303633e-06, -2.77534485e-05],
        [ 5.43072261e-05, -2.77534485e-05,  1.00891325e-04]]),
 0.0010083530589819155)

In [25]:
y = [950, 1300, 800, 1000, 1300]
w= np.dot(np.dot(XTX_inv, XT), y)
w

array([23.12330961, -1.48124183,  5.69922946])

`Answer: 5.6992`